--------------------------- DROP TABLE & SEQUENCE ------------------------------
DROP SEQUENCE MEMBER_SEQ;
DROP TABLE MEMBER_TICKET;
DROP SEQUENCE AT_SEQ;
DROP TABLE AIRLINE_TICKET;
DROP TABLE CITY;
DROP SEQUENCE PL_SEQ;
DROP TABLE PLANE;
DROP SEQUENCE BOARD_SEQ;
DROP TABLE BOARD;
DROP TABLE MEMBER;
DROP TABLE ADMIN;

-------------------------- CREATE TABLE & SEQUENCE ------------------------------
------------------------------ MEMBER & ADMIN ----------------------------------
CREATE TABLE ADMIN (
    adID VARCHAR2(50) PRIMARY KEY,
    adPW VARCHAR2(50) NOT NULL, 
    adNAME VARCHAR2(20) NOT NULL,
    adTEL VARCHAR2(30) NOT NULL
);
CREATE TABLE MEMBER (
    mID     VARCHAR2(50) PRIMARY KEY,
    mPW     VARCHAR2(50) NOT NULL,
    mkNAME  VARCHAR2(50) NOT NULL,
    meNAME  VARCHAR2(20) NOT NULL,
    mTEL    VARCHAR2(30) NOT NULL UNIQUE,
    mEMAIL  VARCHAR2(100) NOT NULL UNIQUE,
    mBIRTH  DATE NOT NULL, 
    mGENDER VARCHAR2(1) NOT NULL,
    mNATION VARCHAR2(10) NOT NULL
);

---------------------------------- AIRLINE -------------------------------------
CREATE TABLE CITY (
    ctNAME VARCHAR2(100) PRIMARY KEY, 
    ctCODE VARCHAR2(10) NOT NULL UNIQUE
);
CREATE TABLE PLANE (
    pLNUM    NUMBER(3) PRIMARY KEY,
    pLCOM    VARCHAR2(50) NOT NULL,
    pLCOMCODE VARCHAR2(10) NOT NULL,
    pLNAME   VARCHAR2(50) NOT NULL,
    pLSEAT   NUMBER(3) NOT NULL
);
CREATE SEQUENCE PL_SEQ
    START WITH 10
    MAXVALUE 999
    INCREMENT BY 3
    NOCACHE
    NOCYCLE;
CREATE TABLE AIRLINE_TICKET (
    atID    VARCHAR2(10) PRIMARY KEY,
    aCTNAME VARCHAR2(100) REFERENCES CITY(ctNAME) NOT NULL,
    dCTNAME VARCHAR2(100) REFERENCES CITY(ctNAME) NOT NULL,
    pLNUM   NUMBER(3) REFERENCES PLANE(pLNUM) NOT NULL UNIQUE,
    atPRICE NUMBER(8) NOT NULL,
    atATIME TIMESTAMP NOT NULL,
    atDTIME TIMESTAMP NOT NULL
);
CREATE SEQUENCE AT_SEQ 
    MAXVALUE 9
    NOCACHE;
CREATE TABLE MEMBER_TICKET (
    rvNUM     NUMBER(11) PRIMARY KEY,
    atID      VARCHAR2(10) REFERENCES AIRLINE_TICKET(atID) NOT NULL,
    mID       VARCHAR2(50) REFERENCES MEMBER(mID) NOT NULL,
    mtSEAT    NUMBER(3) NOT NULL,
    mtSERVICE VARCHAR2(100)
);
CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;

---------------------------------- BOARD ---------------------------------------
CREATE TABLE BOARD (
    bID       NUMBER(5) PRIMARY KEY,
    mID       VARCHAR2(50) NOT NULL REFERENCES MEMBER(mID),
    bSUBJECT  VARCHAR2(45) NOT NULL,
    bCONTENT  VARCHAR2(4000) NOT NULL,
    bFILE     VARCHAR2(100),
    bIP       VARCHAR2(30) NOT NULL,
    BGROUP    NUMBER(3) NOT NULL,
    BSTEP     NUMBER(3) NOT NULL,
    BINDENT   NUMBER(3) NOT NULL,
    bRDATE    DATE DEFAULT SYSDATE
);
CREATE SEQUENCE BOARD_SEQ 
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;











